export const countryMapping = {
  Algeria: "Algeria",
  Angola: "Angola",
  Argentina: "Argentina",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaijan",
  Bahrain: "Bahrain",
  Belgique: "Belgium",
  Belgium: "Belgium",
  België: "Belgium",
  Brasil: "Brazil",
  Brazil: "Brazil",
  Bulgaria: "Bulgaria",
  Canada: "Canada",
  Chile: "Chile",
  China: "China",
  Colombia: "Colombia",
  "Costa Rica": "Costa Rica",
  Croatia: "Croatia",
  "Czech Republic": "Czechia",
  Czechia: "Czechia",
  Danmark: "Denmark",
  Denmark: "Denmark",
  Deutschland: "Germany",
  Germany: "Germany",
  Djibouti: "Djibouti",
  "Dominican Republic": "Dominican Republic",
  Ecuador: "Ecuador",
  Egypt: "Egypt",
  España: "Spain",
  Spain: "Spain",
  Estonia: "Estonia",
  Finland: "Finland",
  France: "France",
  "French Guiana": "French Guiana",
  "French Polynesia": "French Polynesia",
  Georgia: "Georgia",
  Greece: "Greece",
  Guadeloupe: "Guadeloupe",
  "Hong Kong": "Hong Kong",
  Hungary: "Hungary",
  India: "India",
  Indonesia: "Indonesia",
  Ireland: "Ireland",
  Israel: "Israel",
  Italia: "Italy",
  Italy: "Italy",
  Japan: "Japan",
  Kazakhstan: "Kazakhstan",
  Korea: "Korea",
  "La Réunion": "La Réunion",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  Magyarország: "Hungary",
  Malaysia: "Malaysia",
  Martinique: "Martinique",
  Mayotte: "Mayotte",
  Mexico: "Mexico",
  México: "Mexico",
  "Moldova, Republic of": "Moldova",
  Monaco: "Monaco",
  Morocco: "Morocco",
  Nederland: "Netherlands",
  Netherlands: "Netherlands",
  "New Caledonia": "New Caledonia",
  "New Zealand": "New Zealand",
  Norway: "Norway",
  Pakistan: "Pakistan",
  Panamá: "Panama",
  Peru: "Peru",
  Perú: "Peru",
  Philippines: "Philippines",
  Poland: "Poland",
  Polska: "Poland",
  Portugal: "Portugal",
  Romania: "Romania",
  Rwanda: "Rwanda",
  "Saint Barthélemy": "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha": "Saint Helena",
  "Saint-Martin, Caribbean": "Saint-Martin",
  "Saudi Arabia": "Saudi Arabia",
  Schweiz: "Switzerland",
  Serbia: "Serbia",
  "Sierra Leone": "Sierra Leone",
  Singapore: "Singapore",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  Slovensko: "Slovakia",
  "South Africa": "South Africa",
  Suisse: "Switzerland",
  Sverige: "Sweden",
  Svizzera: "Switzerland",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Taiwan: "Taiwan",
  Tanzania: "Tanzania",
  Thailand: "Thailand",
  "The Netherlands": "Netherlands",
  Türkiye: "Turkey",
  Uganda: "Uganda",
  Ukraine: "Ukraine",
  "United Arab Emirates": "United Arab Emirates",
  "United Kingdom": "United Kingdom",
  "United States": "United States",
  "United States of America": "United States",
  Uruguay: "Uruguay",
  "Venezuela, Bolivarian Republic of": "Venezuela",
  "Viet Nam": "Vietnam",
  Österreich: "Austria",
  "Česká republika": "Czechia",
  Казахстан: "Kazakhstan",
  中国: "China",
  台灣: "Taiwan",
  日本: "Japan",
  한국: "Korea",
  Ghana: 'Ghana',
  // SW1H: 'United Kingdom',
  'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom'
};
